package com.zibrinet.split.ui.theme

import androidx.compose.ui.graphics.Color

// Calm teal-green primary with warm gold accents over soft, slightly green
// neutrals. Seeded from #0B5D52.

val PrimaryLight = Color(0xFF0B6B5D)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFA0F2E0)
val OnPrimaryContainerLight = Color(0xFF00201A)
val SecondaryLight = Color(0xFF4B635C)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCDE9DF)
val OnSecondaryContainerLight = Color(0xFF07201A)
val TertiaryLight = Color(0xFF775A0B)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFDF9D)
val OnTertiaryContainerLight = Color(0xFF261A00)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF8FAF6)
val OnBackgroundLight = Color(0xFF191C1A)
val SurfaceLight = Color(0xFFF8FAF6)
val OnSurfaceLight = Color(0xFF191C1A)
val SurfaceVariantLight = Color(0xFFDBE5DF)
val OnSurfaceVariantLight = Color(0xFF3F4945)
val OutlineLight = Color(0xFF6F7975)
val OutlineVariantLight = Color(0xFFBFC9C3)
val InverseSurfaceLight = Color(0xFF2D312E)
val InverseOnSurfaceLight = Color(0xFFEFF1ED)
val InversePrimaryLight = Color(0xFF84D6C4)
val SurfaceContainerLight = Color(0xFFECEEEA)
val SurfaceContainerHighLight = Color(0xFFE6E9E4)
val SurfaceContainerHighestLight = Color(0xFFE1E3DF)
val SurfaceContainerLowLight = Color(0xFFF2F4F0)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)

val PrimaryDark = Color(0xFF84D6C4)
val OnPrimaryDark = Color(0xFF00382F)
val PrimaryContainerDark = Color(0xFF005045)
val OnPrimaryContainerDark = Color(0xFFA0F2E0)
val SecondaryDark = Color(0xFFB1CCC3)
val OnSecondaryDark = Color(0xFF1D352F)
val SecondaryContainerDark = Color(0xFF334B45)
val OnSecondaryContainerDark = Color(0xFFCDE9DF)
val TertiaryDark = Color(0xFFE8C26C)
val OnTertiaryDark = Color(0xFF3F2E00)
val TertiaryContainerDark = Color(0xFF5B4300)
val OnTertiaryContainerDark = Color(0xFFFFDF9D)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF101413)
val OnBackgroundDark = Color(0xFFE0E3E0)
val SurfaceDark = Color(0xFF101413)
val OnSurfaceDark = Color(0xFFE0E3E0)
val SurfaceVariantDark = Color(0xFF3F4945)
val OnSurfaceVariantDark = Color(0xFFBFC9C3)
val OutlineDark = Color(0xFF89938F)
val OutlineVariantDark = Color(0xFF3F4945)
val InverseSurfaceDark = Color(0xFFE0E3E0)
val InverseOnSurfaceDark = Color(0xFF2D312E)
val InversePrimaryDark = Color(0xFF0B6B5D)
val SurfaceContainerDark = Color(0xFF1C201E)
val SurfaceContainerHighDark = Color(0xFF262B29)
val SurfaceContainerHighestDark = Color(0xFF313633)
val SurfaceContainerLowDark = Color(0xFF181C1A)
val SurfaceContainerLowestDark = Color(0xFF0B0F0E)
